apiVersion: v1
kind: Pod

metadata:
  name: myapp-pod
  namespace: myspace
  labels:
    name: myapp-pod
    project: abc
    dept: def

spec:
  containers:
    - name: myapp-container
      image: shongcheng/myapp:v1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3000
      env:
        - name: DB_HOST
          value: some_host
      resources:
        limits:
          cpu: 100m
          memory: 128Mi

