apiVersion: apps/v1
kind: Deployment

metadata:
  name: mydb-deploy
  namespace: myspace
  labels:
    name: mydb-deploy

spec:
  # number of instances
  replicas: 1
  selector:
    matchLabels:
      name: mydb-pod
  template:
    # pod to be deployed
    metadata:
      name: mydb-pod
      namespace: myspace
      labels:
        name: mydb-pod
        project: abc
        dept: def
    spec:
      containers:
        - name: mydb-container
          image: stackupiss/northwind-db:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306

---
apiVersion: v1
kind: Service

metadata:
  name: mydb-svc
  namespace: myspace
  labels:
    name: mydb-svc

spec:
  type: ClusterIP
  selector:
    name: mydb-pod
  ports:
    - port: 3306
      targetPort: 3306
